version: "3"
services:
  postgis:
    image: mdillon/postgis:10-alpine
    environment:
      POSTGRES_PASSWORD: fluctuating
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 41923:5432

volumes:
  data:

