default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
  host: 127.0.0.1
  port: 41923
  username: postgres
  password: fluctuating

development:
  <<: *default
  database: fluctuations_development

test:
  <<: *default
  database: fluctuations_test

production:
  <<: *default
  database: fluctuations_production
  username: fluctuations
  password: <%= ENV['FLUCTUATIONS_DATABASE_PASSWORD'] %>
